name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

    steps:
      # ✅ Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      
      # ✅ Step 4: Build Docker image and tag for both Docker Hub and GHCR
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile \
            --tag imzami/wirevpn:latest \
          

      # ✅ Step 5: Push image to Docker Hub
      - name: Push to Docker Hub
        run: docker push imzami/wirevpn:latest
